name: Publish Release-version to NPM

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Prepare Environment
        run: |
          corepack enable
          yarn
          yarn build
        env:
          CI: true
      - name: Run Linting
        run: |
          yarn lint
        env:
          CI: true

  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['18', '20']
        os: [ubuntu-latest] # [windows-latest, macOS-latest]
    timeout-minutes: 10
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Prepare Environment
        run: |
          corepack enable
          yarn
          yarn build
        env:
          CI: true

      - name: Run unit tests
        run: |
          yarn test
        env:
          CI: true

  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 15

    # only run on master/main branch
    if: github.ref == 'refs/heads/main'

    needs:
      - lint
      - test

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Check if token is set
        id: check-npm-token
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo "env NPM_TOKEN not set!"
          else
            echo "is-ok="1"" >> $GITHUB_OUTPUT
          fi
      - name: Prepare Environment
        if: ${{ steps.check-npm-token.outputs.is-ok }}
        run: |
          corepack enable
          yarn
        env:
          CI: true
      - name: Build
        if: ${{ steps.check-npm-token.outputs.is-ok }}
        run: |
          yarn build
        env:
          CI: true
      - name: Set .npmrc file
        if: ${{ steps.check-npm-token.outputs.is-ok }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          npm whoami
      - name: Publish to NPM
        if: ${{ steps.check-npm-token.outputs.is-ok }}
        run: yarn lerna:publish from-package --no-verify-access --yes
        env:
          CI: true
